### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Antoo5801** [AGIScuipeng/PMPrimer#2]
Hi!

Why I have this error?

pmprimer -f final_out_seqs.fasta -p notlen notsameseq matri -a muscle threshold:0.96 minlen:16 merge primer2 -e minlen:100 maxlen:145 blast:final_out_seqs.fasta  save -d 1
序列集共有序列 26 条 / Number Of Sequece Data is 26
序列集平均长度 150 位 / Everage Length Of Sequece Data is 150 bp
Traceback (most recent call last):
  File "/mnt/projects/apushkin/miniconda3/envs/meltiplex/bin/pmprimer", line 8, in <module>
    sys.exit(entry())
             ^^^^^^^
  File "/mnt/projects/apushkin/miniconda3/envs/meltiplex/lib/python3.11/site-packages/piece/piecentry.py", line 97, in entry
    pc.maintrunk()
  File "/mnt/projects/apushkin/miniconda3/envs/meltiplex/lib/python3.11/site-packages/piece/piecemain.py", line 463, in maintrunk
    pcdp.check_info()
  File "/mnt/projects/apushkin/miniconda3/envs/meltiplex/lib/python3.11/site-packages/piece/piecedataprogress.py", line 126, in check_info
    self._base.baselog('去重后序列集共 {0} 条 / Number After Duplicate Remove is {0}'.format(len(seq_set(self._data))))
                                                                                         ^^^^^^^^^^^^^^^^^^^
  File "/mnt/projects/apushkin/miniconda3/envs/meltiplex/lib/python3.11/site-packages/piece/piecedataprogress.py", line 55, in seq_set
    idsplit = split_all_from_str(id)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/projects/apushkin/miniconda3/envs/meltiplex/lib/python3.11/site-packages/piece/piecebase.py", line 276, in split_all_from_str
    if strsplit[1] == 'Unclassified' or len(strsplit) < 3 : return None
       ~~~~~~~~^^^
IndexError: list index out of range

**Comment by N3R1UM** [comment]
This error has been fixed in the new code, and I will update the version in pypi later.

**Comment by N3R1UM** [comment]
If you are using your own Fasta file, please try to maintain the format of
>id genes species variant subspecies
separated by spaces, and replace the rest with your content except for variant.

**Comment by N3R1UM** [comment]
If you are using your own Fasta file, please try to maintain the format of
`>id genus species variant subspecies`
separated by spaces, and replace the rest with your content except for variant.

**Comment by N3R1UM** [comment]
And parameter `matrix` only supports alignments.
