### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by malinoviylitiy** [AGIScuipeng/PMPrimer#3]
Hello,

I tried pmprimer with dataset “[16S ribosomal RNA (rRNA) genes of Archaea](https://github.com/AGIScuipeng/PMPrimer_datasets/blob/master/Archaea_16SrRNA.rep.mc.fasta.zip)”. But I've got the error `IndexError: list index out of range` using the command from your [readme.md](https://github.com/AGIScuipeng/PMPrimer#0x05-datasets-in-paper):

`pmprimer -f Archaea_16SrRNA.rep.mc.fasta -a threshold:0.85 gaps:1.0 merge primer2 tm:45.0 -e hpcnt:600 save` 

More details:

```
pmprimer -f Archaea_16SrRNA.rep.mc.fasta -a threshold:0.85 gaps:1.0 merge primer2 tm:45.0 -e hpcnt:600 save

探测比对后序列的所有保守区域...
比对后序列的所有保守区域探测完毕
List Of Conservative Regions is : 
[[7818, 8175], [10171, 11015], [11582, 13404]]
List Of Non Conservative Regions is : 
[[8176, 10170], [11016, 11581]]

正在根据保守区间进行引物设计... 3/3
已经根据保守区间完成引物设计

正在根据保守区间进行二次引物提取... 3/3
已经根据保守区间完成二次引物提取

正在生成扩增子候选...
扩增子候选生成完毕 共3个
请注意引物设计和引物评估模块的的熔解温度可能存在差异 / Please Attention TM Of Primer Design Module & Primer Evaluate Maybe Exist Diff

扩增子分辨力为/ Resolution Of Amplicon：
Traceback (most recent call last):
  File "/home/evgen0805/.local/bin/pmprimer", line 8, in <module>
    sys.exit(entry())
  File "/home/evgen0805/.local/lib/python3.10/site-packages/piece/piecentry.py", line 97, in entry
    pc.maintrunk()
  File "/home/evgen0805/.local/lib/python3.10/site-packages/piece/piecemain.py", line 529, in maintrunk
    reso = pcel.evaluate_resolution()
  File "/home/evgen0805/.local/lib/python3.10/site-packages/piece/pieceevaluate.py", line 240, in evaluate_resolution
    idsplit = split_all_from_str(idallstr)
  File "/home/evgen0805/.local/lib/python3.10/site-packages/piece/piecebase.py", line 278, in split_all_from_str
    if (strsplit[3] == 'subsp.' or strsplit[3] == 'variant') and len(strsplit) > 4 :
IndexError: list index out of range
```

What might be causing this, and how could it be fixed?

**Comment by N3R1UM** [comment]
This error has been fixed in the new code, but I forgot to push it to Pypi. I will push the new version to Pypi later.

**Comment by N3R1UM** [comment]
The latest version `1.0.4` has been pushed to pypi. Please upgrade to the latest version.
