### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by NailouZhang** [AGIScuipeng/PMPrimer#4]
我遇见了相同的问题，软件版本是利用PMPrimer安装的，安装版本是1.0.4

pmprimer -p notlen notsameseq  -a muscle threshold:0.80 gaps:1.0 merge primer2  -f  seq.fasta

序列集共有序列 51 条 / Number Of Sequece Data is 51
序列集平均长度 7367 位 / Everage Length Of Sequece Data is 7367 bp
Traceback (most recent call last):
  File "/home/stone/20T/DataBase/SoftwaresEnsembel/MiniConda/envs/PMPrimer/bin/pmprimer", line 8, in <module>
    sys.exit(entry())
             ^^^^^^^
  File "/home/stone/20T/DataBase/SoftwaresEnsembel/MiniConda/envs/PMPrimer/lib/python3.12/site-packages/piece/piecentry.py", line 96, in entry
    pc.maintrunk()
  File "/home/stone/20T/DataBase/SoftwaresEnsembel/MiniConda/envs/PMPrimer/lib/python3.12/site-packages/piece/piecemain.py", line 463, in maintrunk
    pcdp.check_info()
  File "/home/stone/20T/DataBase/SoftwaresEnsembel/MiniConda/envs/PMPrimer/lib/python3.12/site-packages/piece/piecedataprogress.py", line 126, in check_info
    self._base.baselog('去重后序列集共 {0} 条 / Number After Duplicate Remove is {0}'.format(len(seq_set(self._data))))
                                                                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/stone/20T/DataBase/SoftwaresEnsembel/MiniConda/envs/PMPrimer/lib/python3.12/site-packages/piece/piecedataprogress.py", line 55, in seq_set
    idsplit = split_all_from_str(id)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stone/20T/DataBase/SoftwaresEnsembel/MiniConda/envs/PMPrimer/lib/python3.12/site-packages/piece/piecebase.py", line 251, in split_all_from_str
    if strsplit[1] == 'Unclassified' or len(strsplit) < 4 : return None
       ~~~~~~~~^^^
IndexError: list index out of range

**Comment by N3R1UM** [comment]
请确认一下fasta文件序列标记是否是`>id genus species variant subspecies`的格式，中间用空格区分，variant不用改动。

**Comment by N3R1UM** [comment]
相关的异常已经在新代码中处理，并且会针对Fasta文件的异常格式产生告警，新的代码已经推送到pypi版本1.0.5中。
The relevant exceptions have been handled in the new code, and an alarm will be generated for the abnormal format of the Fasta file. The new code has been pushed to pypi version `1.0.5`.
