### ISSUE TITLE
error: ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by virologist** [AGIScuipeng/PMPrimer#7]
Hi, @davidyytan @N3R1UM 

I got an error when I tried to run it.

`pmprimer -f *.fasta -a threshold:0.9 merge primer2 -e minlen:150 maxlen:2000 save`

Error:
```
探测比对后序列的所有保守区域...
比对后序列的所有保守区域探测完毕
List Of Conservative Regions is : 
[[39, 56], [58, 77], [94, 118], [120, 143], [145, 166], [172, 192], [195, 264], [287, 323], [325, 387], [408, 425], [444, 504], [523, 543], [560, 584], [586, 665], [667, 683], [685, 702], [709, 734], [736, 791], [793, 812], [814, 852], [854, 881], [883, 955], [976, 1002], [1027, 1106], [1111, 1163], [1200, 1218], [1220, 1241], [1243, 1301], [1303, 1320], [1345, 1374], [1387, 1404], [1406, 1424], [1435, 1481], [1492, 1508], [1519, 1554], [1561, 1658]]
List Of Non Conservative Regions is : 
[[57, 57], [78, 93], [119, 119], [144, 144], [167, 171], [193, 194], [265, 286], [324, 324], [388, 407], [426, 443], [505, 522], [544, 559], [585, 585], [666, 666], [684, 684], [703, 708], [735, 735], [792, 792], [813, 813], [853, 853], [882, 882], [956, 975], [1003, 1026], [1107, 1110], [1164, 1199], [1219, 1219], [1242, 1242], [1302, 1302], [1321, 1344], [1375, 1386], [1405, 1405], [1425, 1434], [1482, 1491], [1509, 1518], [1555, 1560]]

正在根据保守区间进行引物设计... 36/36
已经根据保守区间完成引物设计

正在根据保守区间进行二次引物提取... 36/36
已经根据保守区间完成二次引物提取

正在生成扩增子候选...
扩增子候选生成完毕 共1个
请注意引物设计和引物评估模块的的熔解温度可能存在差异 / Please Attention TM Of Primer Design Module & Primer Evaluate Maybe Exist Diff

扩增子分辨力为/ Resolution Of Amplicon：
Please try to maintain the format of fasta like >id genus species variant subspecies, separated by spaces, and replace the rest with your content except for variant.
Traceback (most recent call last):
  File "/Users/bio/miniconda3/envs/bio/bin/pmprimer", line 8, in <module>
    sys.exit(entry())
             ^^^^^^^
  File "/Users/bio/miniconda3/envs/bio/lib/python3.12/site-packages/piece/piecentry.py", line 96, in entry
    pc.maintrunk()
  File "/Users/bio/miniconda3/envs/bio/lib/python3.12/site-packages/piece/piecemain.py", line 534, in maintrunk
    reso = pcel.evaluate_resolution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bio/miniconda3/envs/bio/lib/python3.12/site-packages/piece/pieceevaluate.py", line 266, in evaluate_resolution
    self._base.baselog('\n'.join(['{}, 有效长度 {} bp : 属 {}%; 种{:.2f}%; 亚种 {:.2f}%'.format(k, self._effective_len[k], (len(v[0])/genuscnt)*100, (len(v[1])/specnt)*100, (len(v[2])/subcnt)*100) for k, v in reso.items()]))
                                                                                                                    ~~~~~~~~~^~~~~~~~~
ZeroDivisionError: division by zero
```

Another question: can PMPrimer design the multi-primers with a single sequence in the Fasta file?

Yang

**Comment by N3R1UM** [comment]
It seems that there should be a format error, resulting in no statistical information such as genus.If you are using your own Fasta file, please try to maintain the format of
`>id genus species variant subspecies`
separated by spaces, and replace the rest with your content except for variant.
Use single sequence cannot design multi-primers.

**Comment by virologist** [comment]
![image](https://github.com/AGIScuipeng/PMPrimer/assets/54756814/b6fa41f7-5fff-40d9-bb15-3e9d3e932aa2)
![image](https://github.com/AGIScuipeng/PMPrimer/assets/54756814/ab5d116e-20f7-4e35-81dd-5427ea7d8d0e)

**Comment by N3R1UM** [comment]
For some alignments, primers cannot be designed according to the regular TM value of primer3. You may be able to use` -a tm:50.0 `or other TM values to try to design primers.
